name: "OilUhr OCR"
version: "1.0.7"
slug: "oiluhr_ocr"
description: "Liest Zählerstand der Öluhr per ESP32-CAM aus"
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: auto
host_network: true
map:
  - config:rw
options:
  esp_ip: "192.168.178.82"
  poll_interval: 10
  roi_x: 180
  roi_y: 362
  roi_w: 293
  roi_h: 73
  rotation: 0
  horizontal_mirror: false
  vertical_flip: false
  debug: false
schema:
  esp_ip: str
  poll_interval: int(1,3600)
  roi_x: int(0,2000)
  roi_y: int(0,2000)
  roi_w: int(10,2000)
  roi_h: int(10,2000)
  rotation: list(0|90|180|270)
  horizontal_mirror: bool
  vertical_flip: bool
  debug: bool
